import logging

from environs import Env

env = Env()
env.read_env()

DEBUG = env.bool("ROSTER_RUNTIME_DEBUG", False)
LOG = env.str("ROSTER_RUNTIME_LOG", "app.log")
LOG_LEVEL = getattr(logging, env.str("ROSTER_RUNTIME_LOG_LEVEL", "DEBUG"), "DEBUG")

PORT = env.int("ROSTER_RUNTIME_PORT", 7890)

# RabbitMQ Client Config
RABBITMQ_USER = env.str("ROSTER_RUNTIME_RABBITMQ_USER", "guest")
RABBITMQ_PASSWORD = env.str("ROSTER_RUNTIME_RABBITMQ_PASSWORD", "guest")
RABBITMQ_HOST = env.str("ROSTER_RUNTIME_RABBITMQ_HOST", "localhost")
RABBITMQ_PORT = env.int("ROSTER_RUNTIME_RABBITMQ_PORT", 5672)
RABBITMQ_VHOST = env.str("ROSTER_RUNTIME_RABBITMQ_VHOST", "/")


# Roster API Config
ROSTER_API_URL = env.str("ROSTER_RUNTIME_API_URL", "http://localhost:7888/v0.1")
ROSTER_API_EVENTS_PATH = env.str("ROSTER_RUNTIME_API_EVENTS_PATH", "/resource-events")
ROSTER_API_EVENTS_URL = ROSTER_API_URL + ROSTER_API_EVENTS_PATH
ROSTER_API_STATUS_UPDATE_PATH = env.str(
    "ROSTER_RUNTIME_API_STATUS_UPDATE_PATH", "/status-update"
)
ROSTER_API_STATUS_UPDATE_URL = ROSTER_API_URL + ROSTER_API_STATUS_UPDATE_PATH
ROSTER_API_ACTIVITY_PATH = env.str("ROSTER_RUNTIME_API_ACTIVITY_PATH", "/activities")
ROSTER_API_ACTIVITY_URL = ROSTER_API_URL + ROSTER_API_ACTIVITY_PATH
ROSTER_API_AGENTS_PATH = env.str("ROSTER_RUNTIME_API_AGENTS_PATH", "/agents")
ROSTER_API_AGENTS_URL = ROSTER_API_URL + ROSTER_API_AGENTS_PATH
